# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    open-pull-requests-limit: 10
    commit-message:
      prefix: '[skip ci] '
    schedule:
      interval: 'weekly'
    groups:
      update-redux:
        patterns:
          - '@reduxjs/toolkit'
          - 'redux'
          - 'redux-*'
          - 'react-redux'
          - 'reselect'
      update-eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
      update-textlint:
        patterns:
          - 'textlint'
          - 'textlint-*'
      update-babel:
        patterns:
          - 'babel'
          - '@babel/*'
          - 'babel-*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: '[skip ci] '
